#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ErgoAndroidApp.Resource", IsApplication=true)]

namespace ErgoAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int button2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int button3 = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int button_createContacts_geocode = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int button_create_contact = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int chooseContactButton = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int contactDetailDeleteButton = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int contact_detail_button_showMaps = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int contact_detail_name = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int contact_list = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int contact_list_select = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int contacts_add_geocode_dates = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int contacts_create_contact = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int contacts_input_city = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int contacts_input_housenumber = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int contacts_input_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int contacts_input_street = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int contacts_input_zip = 2131034116;
			
			// aapt resource value: 0x7f050019
			public const int distanceFieldText = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int distanceTotal = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int editText1 = 2131034136;
			
			// aapt resource value: 0x7f05000b
			public const int gridLayout1 = 2131034123;
			
			// aapt resource value: 0x7f05001c
			public const int gridLayout2 = 2131034140;
			
			// aapt resource value: 0x7f050012
			public const int input_password = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int input_username = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout1 = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int login_button = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int menuContactsButton = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int menuOrdersButton = 2131034135;
			
			// aapt resource value: 0x7f050014
			public const int myButton = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int orderCreateButton = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int ordersCreateButton = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int orders_list = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int textDistance = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int textName = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int textWhatDone = 2131034146;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactAddDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Contacts = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CustomerSelect = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OrderDetail = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OrderOverview = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int OrderSuperDetail = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
